version: '3.9'

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/development/php-fpm/build/Dockerfile
        environment:
            WEB_SERVER_HOST: 'nginx'
            DATABASE_URL: 'mysql://${MYSQL_USER}:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DB}?serverVersion=8.0'
        volumes:
            - ./application:/var/www/application
            - var:/var/www/application/var
        depends_on:
            - mysql

    nginx:
        build:
            context: .
            dockerfile: ./docker/development/nginx/build/Dockerfile
        ports:
            - '80:80'
        volumes:
            - ./application/public:/var/www/application/public
            - ./docker/development/nginx/etc/conf.d:/etc/nginx/conf.d
        depends_on:
            - php-fpm

    node:
        build:
            context: .
            dockerfile: ./docker/development/node/build/Dockerfile
        volumes:
            - ./application:/var/www/application
        depends_on:
            - php-fpm

    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - database:/var/lib/mysql

volumes:
    database: ~
    var: ~
